version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: dfs-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - flash-sale-net

  redis:
    image: redis:alpine
    container_name: dfs-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flash-sale-net

  api-gateway:
    build: ./api-gateway
    container_name: dfs-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001/api/v1/auth
      - STOCK_SERVICE_URL=http://stock-service:3002/api/v1/stock
      - ORDER_SERVICE_URL=http://order-service:3003/api/v1/orders
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}
    depends_on:
      - auth-service
      - stock-service
      - order-service
    networks:
      - flash-sale-net

  auth-service:
    build: ./auth-service
    container_name: dfs-auth
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/auth_db
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}
    depends_on:
      - mongodb
    networks:
      - flash-sale-net

  stock-service:
    build: ./stock-service
    container_name: dfs-stock
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - flash-sale-net

  order-service:
    build: ./order-service
    container_name: dfs-order
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://mongodb:27017/order_db
      - STOCK_SERVICE_URL=http://stock-service:3002/api/v1/stock
    depends_on:
      - mongodb
    networks:
      - flash-sale-net

networks:
  flash-sale-net:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
