apiVersion: v1
kind: Secret
metadata:
  name: e-com-secrets
  namespace: e-com-ns
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb:27017"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  ACCESS_TOKEN_SECRET: "super_secret_key_123"
  ACCESS_TOKEN_EXPIRY: "1d"

  STOCK_SERVICE_URL: "http://stock-service:3002/api/v1/stock"
  AUTH_SERVICE_URL: "http://auth-service:3001/api/v1/auth"
  ORDER_SERVICE_URL: "http://order-service:3003/api/v1/orders"
